import nodemailer from "nodemailer";

export interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  attachments?: Array<{
    filename: string;
    path?: string;
    content?: Buffer | string;
  }>;
}

export class EmailService {
  private transporter: nodemailer.Transporter | null = null;

  private getTransporter() {
    if (!this.transporter) {
      // Use Resend or SendGrid if API keys are available
      // For development, use Ethereal (test email service)
      if (
        process.env.RESEND_API_KEY ||
        process.env.SENDGRID_API_KEY ||
        process.env.SMTP_HOST
      ) {
        if (process.env.SENDGRID_API_KEY) {
          this.transporter = nodemailer.createTransport({
            host: "smtp.sendgrid.net",
            port: 587,
            secure: false,
            auth: {
              user: "apikey",
              pass: process.env.SENDGRID_API_KEY,
            },
          });
        } else if (process.env.SMTP_HOST) {
          this.transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: parseInt(process.env.SMTP_PORT || "587"),
            secure: process.env.SMTP_SECURE === "true",
            auth: {
              user: process.env.SMTP_USER,
              pass: process.env.SMTP_PASSWORD,
            },
          });
        }
      }

      // Fallback: use mock transport for testing
      if (!this.transporter) {
        this.transporter = nodemailer.createTransport({
          host: "localhost",
          port: 1025,
          ignoreTLS: true,
        });
      }
    }
    return this.transporter;
  }

  async sendReportEmail(
    prospectEmail: string,
    prospectName: string,
    companyName: string,
    wcagScore: number,
    criticalCount: number,
    pdfUrl: string
  ): Promise<boolean> {
    try {
      const transporter = this.getTransporter();

      const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>Your WCAG Accessibility Audit Report</h2>
          
          <p>Hi ${prospectName},</p>
          
          <p>We've completed a comprehensive accessibility audit for <strong>${companyName}</strong>.</p>
          
          <div style="background-color: #f5f5f5; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3>Audit Summary</h3>
            <p><strong>WCAG Score:</strong> ${wcagScore}/100</p>
            <p><strong>Critical Issues:</strong> ${criticalCount}</p>
          </div>
          
          <p>
            <strong>Your website has ${criticalCount > 0 ? "accessibility issues" : "good accessibility practices"} that ${criticalCount > 5 ? "require" : criticalCount > 0 ? "may need" : "could benefit from"} immediate attention.</strong>
          </p>
          
          <p>
            Recent ADA lawsuits have resulted in settlements ranging from $50,000 to $450,000. Addressing these issues now can save your organization significant legal and financial exposure.
          </p>
          
          <div style="margin: 30px 0;">
            <a href="${pdfUrl}" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block;">
              Download Full PDF Report
            </a>
          </div>
          
          <div style="background-color: #e8f4f8; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #007bff;">
            <h4>Next Steps</h4>
            <p>Ready to fix these issues? Schedule a free 30-minute consultation with our accessibility experts.</p>
            <a href="https://calendly.com/your-calendar" style="background-color: #28a745; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block;">
              Schedule Free Consultation
            </a>
          </div>
          
          <p style="color: #666; font-size: 12px; margin-top: 40px;">
            This report was generated by WCAG AI - AI-Powered Accessibility Consulting<br>
            <a href="https://wcag-ai.com" style="color: #007bff; text-decoration: none;">www.wcag-ai.com</a>
          </p>
        </div>
      `;

      const info = await transporter.sendMail({
        from: process.env.EMAIL_FROM || "noreply@wcag-ai.com",
        to: prospectEmail,
        subject: `${companyName} - WCAG Accessibility Audit Report (Score: ${wcagScore}/100)`,
        html,
        attachments: pdfUrl
          ? [
              {
                filename: `audit-report-${Date.now()}.pdf`,
                path: pdfUrl,
              },
            ]
          : undefined,
      });

      console.log("Email sent successfully:", info.messageId);
      return true;
    } catch (error) {
      console.error("Failed to send email:", error);
      return false;
    }
  }

  async sendOutreachEmail(
    prospectEmail: string,
    prospectName: string,
    companyName: string
  ): Promise<boolean> {
    try {
      const transporter = this.getTransporter();

      const html = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2>Free Accessibility Audit for ${companyName}</h2>
          
          <p>Hi ${prospectName},</p>
          
          <p>We specialize in making websites accessible and legally compliant with WCAG standards.</p>
          
          <p>In just 5 minutes, we can scan ${companyName}'s website and provide a detailed accessibility report that shows:</p>
          
          <ul style="padding-left: 20px;">
            <li>Critical accessibility violations</li>
            <li>Legal risk assessment</li>
            <li>Estimated remediation timeline and cost</li>
            <li>Actionable recommendations</li>
          </ul>
          
          <div style="background-color: #fff3cd; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ffc107;">
            <p><strong>⚠️ Did you know?</strong> Companies face legal action under the ADA for inaccessible websites. Recent settlements have reached $450,000+.</p>
          </div>
          
          <p>
            <strong>This quick audit is completely free and takes just 5 minutes.</strong> No obligation.
          </p>
          
          <div style="margin: 30px 0;">
            <a href="https://wcag-ai.com/quick-win" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block;">
              Get Your Free Audit Now
            </a>
          </div>
          
          <p style="color: #666; font-size: 12px; margin-top: 40px;">
            WCAG AI - AI-Powered Accessibility Consulting
          </p>
        </div>
      `;

      const info = await transporter.sendMail({
        from: process.env.EMAIL_FROM || "noreply@wcag-ai.com",
        to: prospectEmail,
        subject: `Free WCAG Accessibility Audit for ${companyName}`,
        html,
      });

      console.log("Outreach email sent successfully:", info.messageId);
      return true;
    } catch (error) {
      console.error("Failed to send outreach email:", error);
      return false;
    }
  }
}

export const emailService = new EmailService();
